# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.06402813 0.44305427 0.35988889]
  [0.60394522 0.85178906 0.10142201]
  [0.11437645 0.53203287 0.6364239 ]]

 [[0.56938851 0.43937558 0.30324846]
  [0.32579558 0.84564386 0.66111162]
  [0.44567901 0.96325201 0.92151178]]

 [[0.7758588  0.28904396 0.31885528]
  [0.81782675 0.66060053 0.40302118]
  [0.24960626 0.92140302 0.86786449]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

# 5.  How to find common values between two arrays?

In [4]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))



Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [5]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [6]:
a = np.random.randint(0,2,6)
print("First array:")
print(a)
b = np.random.randint(0,2,6)
print("Second array:")
print(b)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(a, b)
print(array_equal)

First array:
[1 0 1 1 0 1]
Second array:
[0 1 0 1 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [3]:
x = np.random.random(10)
print("Original array:")


Original array:
[0.11052451 0.07329349 0.4010787  0.65657001 0.7869338  0.6392652
 0.49530627 0.60913762 0.52714426 0.77601419]
Sorted array:
[0.07329349 0.11052451 0.4010787  0.49530627 0.52714426 0.60913762
 0.6392652  0.65657001 0.77601419 0.7869338 ]


# 9. How to print all the values of an array?

In [7]:
aa = np.random.random(100)
 
for i in range(0, len(aa)):    
    print(aa[i]),    

0.5022538001738969
0.35412362202470804
0.7254466317200071
0.7397364324345912
0.11619647456353555
0.273503132294697
0.8817638173457902
0.7971611469611569
0.4735677438815018
0.5595828562310885
0.3979710655815134
0.2685366797203096
0.25560716741780687
0.1298167022269009
0.5388130686960353
0.1950169039433145
0.1910725926632213
0.3620526518449245
0.8135528464413212
0.11276643028555933
0.41230809545552893
0.48777374047309974
0.4766699627275113
0.09674967627739617
0.5789004158878565
0.1628565744928282
0.21463245944054254
0.17401640304324706
0.12097383731089884
0.4386223521214122
0.1865801232855211
0.13829534130806076
0.41886125715908684
0.18455771489453976
0.6853706757239593
0.8308276994891886
0.40312209287678147
0.57078900791008
0.8649042871226394
0.04081970468192986
0.027771273901797233
0.26866663513018996
0.09148020513058974
0.3778943528640233
0.8646812520223665
0.41153312241328976
0.15144277932190853
0.2966852173898604
0.5747410377711825
0.5052720032194137
0.3976245975411419
0.24300812144

# 10.Subtract the mean of each row of a matrix

In [8]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.30058553 0.81236452 0.19306991 0.3109196  0.36374977 0.31101341
  0.00746096 0.65201922 0.36722199 0.24443696]
 [0.28132112 0.73814858 0.60688173 0.28126194 0.9221826  0.59805588
  0.79820269 0.55475321 0.22653061 0.73064324]
 [0.89075236 0.43700265 0.35693373 0.45871838 0.47947421 0.35871781
  0.01540413 0.2112671  0.69082478 0.53740273]
 [0.27506337 0.33665582 0.06294002 0.03300871 0.50955617 0.55368862
  0.84038836 0.90096461 0.35804103 0.06038285]
 [0.40594596 0.27559048 0.92561812 0.13411993 0.11910562 0.67029421
  0.22213854 0.6866831  0.82441838 0.74556006]]

Subtract the mean of each row of the said matrix:

[[-0.05569866  0.45608034 -0.16321427 -0.04536458  0.00746558 -0.04527078
  -0.34882322  0.29573503  0.0109378  -0.11184723]
 [-0.29247704  0.16435042  0.03308357 -0.29253622  0.34838444  0.02425772
   0.22440453 -0.01904495 -0.34726755  0.15684508]
 [ 0.44710257 -0.00664714 -0.08671606  0.0150686   0.03582442 -0.08493197
  -0.42824566 -0.23238269  0.2

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [11]:
 a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)

np.diag(np.dot(np.dot(a, b), a.T))


array([  60,  672, 1932, 3840, 6396])

# 13.How to find the most frequent value in an array?

In [14]:
arr = [1, 3, 2, 1, 4, 1]


# 14.How to get the n largest values of an array

In [15]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [16]:
import numpy as np
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
